### ISSUE TITLE
4.3.1 Error

### ISSUE THREAD

**Issue by R2turnTrue** [devproje/InventoryGUI#24]
```
[15:32:46 WARN]: java.lang.ExceptionInInitializerError
[15:32:46 WARN]:        at net.projecttl.inventory.gui.SimpleInventoryBuilder.<init>(SimpleInventoryBuilder.kt:35)
[15:32:46 WARN]:        at net.projecttl.inventory.InventoryGUIKt.gui(InventoryGUI.kt:54)
[15:32:46 WARN]:        at routine-bukkit-1.0-SNAPSHOT-all.jar//xyz.r2turntrue.routine.bukkit.RoutineMenu.open(RoutineMenu.kt:16)
[15:32:46 WARN]:        at routine-bukkit-1.0-SNAPSHOT-all.jar//xyz.r2turntrue.routine.bukkit.RoutineCommand$init$1$2$2.invoke(RoutineCommand.kt:17)
[15:32:46 WARN]:        at routine-bukkit-1.0-SNAPSHOT-all.jar//xyz.r2turntrue.routine.bukkit.RoutineCommand$init$1$2$2.invoke(RoutineCommand.kt:16)
[15:32:46 WARN]:        at io.github.monun.kommand.v1_17_1.NMSKommandKt.convert$lambda-14$lambda-12$lambda-11(NMSKommand.kt:136)
[15:32:46 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
[15:32:46 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177)
[15:32:46 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:282)
[15:32:46 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45)
[15:32:46 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[15:32:46 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
[15:32:46 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2262)
[15:32:46 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2073)
[15:32:46 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2054)
[15:32:46 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[15:32:46 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[15:32:46 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[15:32:46 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:32:46 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[15:32:46 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[15:32:46 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1426)
[15:32:46 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[15:32:46 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[15:32:46 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1404)
[15:32:46 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1397)
[15:32:46 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[15:32:46 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1375)
[15:32:46 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1286)
[15:32:46 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[15:32:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[15:32:46 WARN]: Caused by: org.bukkit.plugin.InvalidPluginException: Should be loaded by a plugin
[15:32:46 WARN]:        at net.projecttl.inventory.InventoryGUI.plugin$lambda-0$checkLoader(InventoryGUI.kt:35)
[15:32:46 WARN]:        at net.projecttl.inventory.InventoryGUI.plugin$lambda-0$checkLoader(InventoryGUI.kt:36)
[15:32:46 WARN]:        at net.projecttl.inventory.InventoryGUI.plugin$lambda-0$checkLoader(InventoryGUI.kt:36)
[15:32:46 WARN]:        at net.projecttl.inventory.InventoryGUI.<clinit>(InventoryGUI.kt:40)
[15:32:46 WARN]:        ... 31 more
```

**Comment by R2turnTrue** [comment]
Bukkit 1.17.1, Paper 402

**Comment by R2turnTrue** [comment]
이 오류를 해결할 PR을 #25 에 올려뒀습니다.

**Comment by devproje** [comment]
확인했습니다. 머지 했으니 이슈 닫도록 하겠습니다.
